### ISSUE TITLE
Es mejor poner ['*']

### ISSUE THREAD

**Issue by emper0r** [dcruz1990/django-misclientes#2]
https://github.com/dcruz1990/django-misclientes/blob/4c7c409e6f8e8d3dc3971b0054bbc4191c011509/clients/settings.py#L32

- Deberias dejarlo abierto a todos con alguna nota de aviso sino no podran ver la app a menos que usen esos IPs

**Comment by emper0r** [comment]
rectifico. gracias a @c0x6A
mejor mete una variable y luego la usas en allowed_hosts pero aclarando la variable da setear en el readme

**Comment by dcruz1990** [comment]
Si, es que en ese caso se me quedaron las IPs que use para el despliegue en la empresa. Cuando ande mas veloz rectifico :D

**Comment by mrbrazzi** [comment]
Ya no se necesita hacer lo que plantean... con la inclusión del fichero .env, cada cual puede establecer los valores que necesite... para más detalles revisar el fichero **.env-sample**

**Comment by dcruz1990** [comment]
Perfecto.. cierro aqui :D
